version: "3"
services:
  inventario-app:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url" : "jdbc:mysql://mysql:3306/inventario?allowPublicKeyRetrieval=true&useSSL=false",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "1jerete1",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1jerete1"
      MYSQL_DATABASE: "inventario"
    volumes:
      - mysqldb:/var/lib/mysql
volumes:
  mysqldb: