server:
  port: 8085


spring:
  datasource:
    url: jdbc:mysql://localhost:3307/inventario
    username: root
    password: 1jerete1

  hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: true
    format_sql: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      platform: mysql
      data-locations: 'classpath:db/*.sql'