server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventario
    username: root
    password: 1jerete1

  hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: true
    format_sql: true

  jpa:
    hibernate:
      ddl-auto: update